FROM osrf/ros:jazzy-desktop

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    libgl1-mesa-dev \
    libgl1 \
    libglew-dev \
    libosmesa6-dev \
    patchelf \
    python3 \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

ENV VENV=/opt/venv
RUN python3 -m venv --system-site-packages $VENV
ENV PATH="$VENV/bin:$PATH"

RUN pip install --no-cache-dir --upgrade pip setuptools wheel && \
    pip install --no-cache-dir mujoco numpy

RUN rosdep update

COPY ./config/fastdds.xml /fastdds.xml

WORKDIR /vla_ur
COPY src src

RUN rosdep install --from-paths src --ignore-src -y --rosdistro $ROS_DISTRO

RUN source /opt/ros/jazzy/setup.bash \
    && colcon build --symlink-install

RUN echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc
RUN echo "source /vla_ur/install/setup.bash" >> ~/.bashrc

CMD ["bash"]