FROM osrf/ros:jazzy-desktop

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    libglfw3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY ./config/fastdds.xml /fastdds.xml

RUN git clone https://github.com/google-deepmind/mujoco.git \
    && cd mujoco \
    && cmake -B build -DCMAKE_BUILD_TYPE=Release \
    && cmake --build build \
    && cmake --install build \
    && cd .. \
    && rm -rf mujoco

WORKDIR /vla_ur
COPY src src

RUN rosdep update \
    && rosdep install --from-paths src --ignore-src -y --rosdistro $ROS_DISTRO

RUN source /opt/ros/jazzy/setup.bash \
    && colcon build --symlink-install

RUN echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc
RUN echo "source /vla_ur/install/setup.bash" >> ~/.bashrc

CMD ["bash"]